apiVersion: devopstoolkitseries.com/v1alpha1
kind: CompositeKubernetesCluster
metadata:
  name: team-a
  labels:
    cluster-owner: me
spec:
  compositionRef:
    # Possible values cluster-google, cluster-azuer, cluster-aws
    name: cluster-google
  parameters:
    # Possible values small, medium, large
    nodeSize: small
    # version: "1.20"
    minNodeCount: 2
  writeConnectionSecretToRef:
    namespace: team-a
    name: cluster
